apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment-{ACCOUNT_ID}
  labels:
    app: account-{ACCOUNT_ID}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-{ACCOUNT_ID}
  template:
    metadata:
      labels:
        app: account-{ACCOUNT_ID}
    spec:
      containers:
        - name: manager
          image: dsp-manager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: ACCOUNT_ID
              value: {ACCOUNT_ID}
        - name: client-1
          image: dsp-client:latest
          imagePullPolicy: IfNotPresent
        - name: client-2
          image: dsp-client:latest
          imagePullPolicy: IfNotPresent
