apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-deployment
  labels:
    app: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: dsp-monitor:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-service
spec:
  type: NodePort
  selector:
    app: monitor
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30081
